# Generated by Django 5.1.7 on 2025-05-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_review_order_reviewreply_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
