# Generated by Django 5.1.7 on 2025-05-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('staff', 'Staff'), ('owner', 'Owner')], max_length=20, null=True),
        ),
    ]
