"""
Django settings for tabletap project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4p3$4%&ez*5%_lvf9^!s&^veh50@%qw04-dg$sb4ofms!*(s(@"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["infs3202-4582d0a5.uqcloud.net"]

CSRF_TRUSTED_ORIGINS = ["https://4582d0a5.uqcloud.net","https://infs3202-4582d0a5.uqcloud.net"]

OPENAI_API_KEY = "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"



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sites',
    "tables",
     # The following apps are required:
    'allauth',
    'allauth.account',
    

    # Required for Social Auth Support`.
    'allauth.socialaccount',
    # Required Provider:
    'allauth.socialaccount.providers.google',

]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
    "tables.middleware.SingleSessionMiddleware",
    "tables.middleware.EnforceSingleLoginMiddleware",
]

ROOT_URLCONF = "tabletap.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tabletap.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'tabletap',  # 数据库名字
#         'USER': 'root',
#         'PASSWORD': 'Ysy030601-yskm',
#         'HOST': '127.0.0.1',  # 那台机器安装了MySQL
#         'PORT': 3306,
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tabletap_db',
        'USER': 'root',
        'PASSWORD': '0a5a6250c431f0a4f98c6ed6',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Australia/Brisbane"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# settings.py

STATIC_URL = 'tabletap_static/'

# The directory where collectstatic will place all static files
STATIC_ROOT = "/var/www/htdocs/tabletap_static/"  # This is within the Nginx web root folder

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTHENTICATION_BACKENDS = [
    
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
    
]

# Add the Google Account Client-id and Secret from your JSON download

# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'APP': {
#             'client_id': '191891477451-5oae5l01gc8rgvnj97567t2ikt2qmc73.apps.googleusercontent.com',
#             'secret': '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',
          
#         },
#         'SCOPE': ['profile','email',],
#         'AUTH_PARAMS': {'access_type': 'online'},
#         'METHOD': 'oauth2',
#         'VERIFIED_EMAIL': True,
#     }
   
# }

LOGIN_REDIRECT_URL = 'role_redirect'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'home'
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL='https'